FROM node:16 as build-stage
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build"]

FROM nginx:1.15
COPY --from=build-stage /usr/src/app/build/ /usr/share/nginx/html
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
