version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: wobble-server-dc
    container_name: wobble-node-server-dc
    command: npm run server
    ports:
      - "5000:5000"
    depends_on:
      - redisdb
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: wobble-client-dc
    container_name: wobble-node-client-dc
    command: npm run start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

  redisdb:
    image: 'redis:alpine'
    restart: always
    hostname: redisdb
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - app-network

networks:
    app-network:
        driver: bridge